version: "3.8"

services:
  server:
    # image: nginx:stable-alpine
    # prod ready modification copy src to image instead of mirror bind mount
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql:8.1.0

    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile

    volumes:
      - ./src:/var/www/html/
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html/
